### ISSUE TITLE
Create initial Homepage

### ISSUE THREAD

**Issue by ayoayco** [pistangmapa/2019#1]
Hi guys! I plan to use [Jekyll](https://jekyllrb.com) for the framework and Github Pages for hosting because it's free. Updating the content will be done either by doing git commits and push or using Github to edit the files in the repository. See [this documentation](https://jekyllrb.com/docs/pages/) for content management using Jekyll.

We can use the address [https://pistangmapa.github.io/2019](https://pistangmapa.github.io/2019) for this website, but we can use a custom domain too.

Let me know if this is good or if you have any ideas/questions. 😄 

I plan to start this weekend with a simple homepage similar to [Maptime Diliman's website](http://maptimediliman.github.io/) with links to the content currently here in the repository.

**Comment by seav** [comment]
My opinion: While we might have the funds to register a domain name, I don't think we really need it. We managed to survive organizing the conference without having an actual standalone website and just piggybacking on the Tito ticketing service.

**Comment by ayoayco** [comment]
Yup! The free github.io domain will suffice for now.

**Comment by maning** [comment]
Danke @ayoayco!  To help you get started I'll be uploading a couple of md files later (program, coc).

**Comment by ayoayco** [comment]
Done with the initial home page. Will work on adding other contents and some look and feel improvements next.
