### ISSUE TITLE
Merge downloads to program page?

### ISSUE THREAD

**Issue by govvin** [pistangmapa/2019#3]
@ayoayco , what do you think of merging the [download](https://pistangmapa.github.io/2019/downloads/) page to the [program](https://pistangmapa.github.io/2019/2019/08/09/program.html) page made by Maning? Seems like there are placeholders ready to link files and videos, when they're ready.

**Comment by ayoayco** [comment]
Yup I will do that. I planned to update the placeholder links but didn't
get the time the past weekend.

**Comment by govvin** [comment]
Thank you, Ayoo!
